jenkinsci/jclouds-plugin

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate.java
pom.xml

Upgrade to jclouds 1.8.1 and revert eh security groups change as it is now fixed (see [JCLOUDS-496](https://issues.apache.org/jira/browse/JCLOUDS-496)).

Upgrade to jclouds 1.8.1

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlave.java

This PR uses a java.util.concurrent.locks.Condition.await(...) instead of Thread.sleep(), thus eliminating the need for PR #85 while achieving the same (resp. even better) performance improvement.

Improve wait for phone-home, replacing PR #85

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlave.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate.java
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsComputer/configure.jelly
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate/config.jelly
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplateTest.java

Allow ability to configure the usage mode of a dynamic mode, NORMAL or EXCLUSIVE.

[JENKINS-25865] Add ability to configure node usage mode.

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsCloud.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlave.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsCloudInsideJenkinsLiveTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsCloudLiveTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsCloudTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplateTest.java

Alexey on GitHub ask fix npe retention time

---

jclouds-shaded/pom.xml

@felfert based on our group [conversation](https://groups.google.com/forum/#!topic/jenkinsci-users/2LF4kGPs3p8) i have added a couple of dependencies that are both complete.
Please let me know if the dependencies look ok.
Thanks.

Add provider dependency

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/blobstore/BlobStoreProfile.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsCloud.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/modules/JenkinsBouncyCastleCrypto.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/modules/JenkinsConfigurationModule.java

see [JENKINS-47967](https://issues.jenkins-ci.org/browse/JENKINS-47967)

[JENKINS-47967] workaround JCE Providers memory leak

---

pom.xml

Makes it easier to reuse and debug

Build sources jar for shaded package

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/blobstore/BlobStoreProfile.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/blobstore/BlobStoreProfileTest.java

... and are aware of newly added or accidentally
removed storage providers.

Added test to ensure we have all the cloud storage providers we want

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsOneOffSlave.java

inspired by this pr: https://github.com/jenkinsci/mesos-plugin/pull/277
please let me know any concerns or anything we might need to change.

Convert JCloudsOneOffSlave to a SimpleBuildWrapper so that it may be used from Pipeline scripts

---

pom.xml

Saw while looking through the pom

https for scm url

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsComputer.java

`pendig` > `pending`
Signed-off-by: Major Hayden <major@redhat.com>

Trivial spelling fix

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsBuildWrapper.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsCloud.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsJnlpLauncher.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlave.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/MetaDataPublisher.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/internal/JCloudsNodeMetadata.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/internal/NodePlan.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/internal/ProvisionPlannedInstancesAndDestroyAllOnError.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/internal/RetryOnExceptionSupplier.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/internal/RunningNode.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/config/ConfigDataSource.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/config/ConfigHelper.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/internal/JnlpProvisionCrumbExclusion.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/internal/JnlpProvisionWebHook.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/internal/ReplaceHelper.java
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate/config.jelly
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate/help-jnlpProvision.html
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplateTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/MigrationTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/UserDataConverterTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/internal/TerminateNodesTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/config/UserDataTest.java

This PR introduces a new JNLP-related checkbox in slave templates. If set, support for
provisioning JNLP agents (URLs and secret) on virtual machines is enabled.

Add ability to provision JNLP-related metadata.

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/CloudInstanceDefaults.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsCloud.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsComputer.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsRetentionStrategy.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlave.java
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsCloud/config.jelly
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsCloud/help-errorRetentionTime.html
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsCloudInsideJenkinsLiveTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsCloudTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplateTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/MigrationTest.java
pom.xml

Implement cleanup of nodes that experience failures at agent startup.

Enhance error handling

---

src/main/java/jenkins/plugins/jclouds/blobstore/BlobStoreProfile.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsCloud.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsComputer.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsTemplatesCommand.java
src/main/java/jenkins/plugins/jclouds/compute/PhoneHomeMonitor.java
src/main/java/jenkins/plugins/jclouds/compute/internal/ProvisionPlannedInstancesAndDestroyAllOnError.java
src/main/java/jenkins/plugins/jclouds/internal/CredentialsHelper.java

- [N/A] Link to relevant pull requests, esp. upstream and downstream changes
- [N/A] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Prepare for core upgrade to Guava 30.1.1

---

src/main/java/jenkins/plugins/jclouds/compute/JCloudsBuildWrapper.java
src/main/java/jenkins/plugins/jclouds/compute/internal/ProvisionPlannedInstancesAndDestroyAllOnError.java

Don't need tearDown if no nodes are startet

---

src/main/java/jenkins/plugins/jclouds/compute/JCloudsBuildWrapper.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsCloud.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlave.java
src/main/java/jenkins/plugins/jclouds/compute/MetaDataPublisher.java
src/main/resources/jenkins/plugins/jclouds/compute/JCloudsBuildWrapper/config.jelly
src/main/resources/jenkins/plugins/jclouds/compute/JCloudsBuildWrapper/help-publishMeta.html

- Implement optional publishMeta parameter
- Publish JCLOUDS_SUPPLEMENTAL_INDEX for supplemental nodes

Improve JCloudsBuildWrapper

---

src/main/java/jenkins/plugins/jclouds/compute/JCloudsBuildWrapper.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsCloud.java
src/main/resources/jenkins/plugins/jclouds/compute/JCloudsBuildWrapper/config.jelly
src/main/resources/jenkins/plugins/jclouds/compute/JCloudsBuildWrapper/help-envVarName.html
src/main/resources/jenkins/plugins/jclouds/compute/JCloudsBuildWrapper/help-indexName.html
src/main/resources/jenkins/plugins/jclouds/compute/JCloudsBuildWrapper/help-publishMeta.html

Make name of index variable configurable

---

pom.xml
src/main/java/jenkins/plugins/jclouds/config/ConfigDataSource.java
src/main/java/jenkins/plugins/jclouds/config/ConfigHelper.java

Migrate to Jakarta Mail

---

.mvn/extensions.xml
Jenkinsfile
pom.xml
src/main/java/jenkins/plugins/jclouds/config/ConfigHelper.java
src/test/java/jenkins/plugins/jclouds/compute/JCloudsCloudTest.java

Refresh plugin for June 2023

---

src/main/webapp/jclouds.js

This PR removes dependency on Prototype.js which got removed in jenkins 2.426.1.
```[tasklist]
```

Remove dependency on Prototype.js

---

JNLPPROVISIONING-pre35.md
README.md
pom.xml
src/main/java/jenkins/plugins/jclouds/blobstore/BlobStoreProfile.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsCloud.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsComputer.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsJnlpLauncher.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlave.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate.java
src/main/resources/jenkins/plugins/jclouds/compute/JCloudsComputer/index-top.jelly
src/main/resources/jenkins/plugins/jclouds/compute/JCloudsComputer/index.jelly
src/main/resources/jenkins/plugins/jclouds/compute/JCloudsComputer/index.properties
src/main/resources/jenkins/plugins/jclouds/compute/JCloudsJnlpLauncher/main.jelly
src/main/resources/jenkins/plugins/jclouds/compute/JCloudsJnlpLauncher/main.properties
src/main/resources/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate/config.jelly
src/main/resources/jenkins/plugins/jclouds/compute/UserData/config.jelly
src/main/resources/lib/jclouds/blockWrapper.jelly
src/main/webapp/jclouds.js
src/test/java/jenkins/plugins/jclouds/compute/JCloudsCloudTest.java

Main motivation was the deprecation of the `-jnlpUrl` parameter. While working
on the code, I stumbled over some other obsolete parts.
- Support new agent.jar parameters
- Adapted GUI buttons to new core style
- Removed obsolete conditional in blockWrapper (GUI)
- Fixed javascript compatibility in GUI
- Disable node description editor for JCloudsComputer
- Removed obsolete workaround for Jenkins.updateNode()
- Updated docs
- Fixed some deprecation warnings
```[tasklist]
```

Fixup compatibility with jenkins >= 2.440.1

---

pom.xml

Signed-off-by: Olivier Lamy <olamy@apache.org>

use eddsa-api plugin for eddsa library

---

.mvn/extensions.xml
pom.xml
src/main/java/jenkins/plugins/jclouds/credentials/OpenstackKeystoneV3.java
src/main/java/jenkins/plugins/jclouds/internal/CredentialsHelper.java

Bump up baseline to 2.462

---

src/main/java/jenkins/plugins/jclouds/compute/JCloudsCloud.java
src/main/resources/jenkins/plugins/jclouds/compute/JCloudsCloud/computerSet.jelly
src/main/resources/jenkins/plugins/jclouds/compute/JCloudsCloud/provision.js
src/main/resources/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate/config.jelly
src/main/resources/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate/managecf.js
src/main/resources/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate/showcf.js
src/main/resources/jenkins/plugins/jclouds/compute/UserData/config.jelly
src/main/webapp/jclouds.js

Removed dependency on YUI in manual provisioning UI
Removed dependency on YUI in template configuration UI
Fixes [JENKINS-73549](https://issues.jenkins.io/browse/JENKINS-73549)

Fix jenkins 73549

---

pom.xml
src/main/java/jenkins/plugins/jclouds/blobstore/BlobStorePublisher.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsCloud.java
src/main/java/jenkins/plugins/jclouds/credentials/JCloudsUserWithKey.java
src/main/java/jenkins/plugins/jclouds/internal/JnlpProvisionCrumbExclusion.java
src/main/java/jenkins/plugins/jclouds/internal/JnlpProvisionWebHook.java
src/main/java/jenkins/plugins/jclouds/internal/PhoneHomeCrumbExclusion.java
src/main/java/jenkins/plugins/jclouds/internal/PhoneHomeWebHook.java

Migrate from deprecated EE 8 methods to non-deprecated EE 9 equivalents.

Migrate from EE 8 to EE 9

---

src/test/java/jenkins/plugins/jclouds/blobstore/BlobStoreProfileInsideJenkinsLiveTest.java
src/test/java/jenkins/plugins/jclouds/blobstore/BlobStoreProfileTest.java
src/test/java/jenkins/plugins/jclouds/blobstore/BlobStoreTestFixture.java
src/test/java/jenkins/plugins/jclouds/compute/ComputeTestFixture.java
src/test/java/jenkins/plugins/jclouds/compute/JCloudsCloudInsideJenkinsLiveTest.java
src/test/java/jenkins/plugins/jclouds/compute/JCloudsCloudTest.java
src/test/java/jenkins/plugins/jclouds/compute/JCloudsProfileTest.java
src/test/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplateTest.java
src/test/java/jenkins/plugins/jclouds/compute/UserDataConverterTest.java
src/test/java/jenkins/plugins/jclouds/compute/internal/TerminateNodesTest.java
src/test/java/jenkins/plugins/jclouds/config/UserDataTest.java
src/test/java/jenkins/plugins/jclouds/internal/SSHPublicKeyExtractorTest.java

This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations
* Migrate assertions
* Minor cleanup
* Remove public visibility of test classes and methods
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewd.
If there are any questions, please do not hesitate to ping me.

Migrate tests to JUnit5

---

pom.xml
src/main/java/jenkins/plugins/jclouds/blobstore/BlobStoreProfile.java
src/main/java/jenkins/plugins/jclouds/blobstore/BlobStorePublisher.java
src/main/java/jenkins/plugins/jclouds/compute/InstancesToRun.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsCloud.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsComputer.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsOfflineStep.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlave.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate.java
src/main/java/jenkins/plugins/jclouds/compute/UserData.java

* Mostly adding permission checks and/or RequirePOST annotations
* Fixed a few cases where plaintext credential might be stored
* Rest are false positives

Fixed warnings from jenkins-security-scan

---

src/main/resources/jenkins/plugins/jclouds/compute/JCloudsJnlpLauncher/main.jelly

Migrate from EE 8 to EE 9 in Jelly view

---

src/main/java/jenkins/plugins/jclouds/compute/JCloudsCloud.java

This PR fixes [JENKINS-63731](https://issues.jenkins.io/browse/JENKINS-63731)
Tested with both manual provisioning in the /computer view and attempting to run a pipeline containing more than maxInstances parallel stages where each requires a new agent instance.

Fix JENKINS-63731 (broken instance cap check)

---

src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate.java

Migrate from deprecated/EOL Commons Lang 2 to native Java Platform
Tested manually

Remove usages of Commons Lang 2
