jclouds-plugin/pom.xml
jclouds-plugin/src/findbugs/excludesFilter.xml
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsCloud.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlave.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/internal/SSHPublicKeyExtractor.java
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsCloud/config.jelly
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsCloud/help-cloudGlobalKeyId.html
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsCloud/help-privateKey.html
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsCloud/help-publicKey.html
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate/config.jelly
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate/help-credentialsId.html
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate/help-jenkinsUser.html
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate/help-overrideRetentionTime.html
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate/help-preExistingJenkinsUser.html
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsCloudInsideJenkinsLiveTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsCloudLiveTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsCloudTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplateTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/internal/SSHPublicKeyExtractorTest.java

Hi,
This is my next iteration which contains all the stuff we discussed:
- Use existing credentials framework of jenkins everywhere, except with the main cloud username/passsword.
- Auto-migration of config data from the old plugin version
- Added findbugs and PMD checks (both currently set to non-fatal, so the show a lot of errors/warnings but do not fail the build)
- Added translation tags in the main config.jelly
- Removed JDK installer
Cheers
-Fritz

Use existing credentials framework of jenkins

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate.java

Previously, setting autoAssingFloatingIp option to true
threw a NullPointerException.
Calling the method shouldAutoAssignFloatingIp() seems to fixes
this problem.

[JENKINS-26083] Fix floating ip bug on openstack

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/CloudInstanceDefaults.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsCloud.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlave.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsCloudInsideJenkinsLiveTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsCloudLiveTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsCloudTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplateTest.java

I documented the bug here: https://issues.jenkins-ci.org/browse/JENKINS-29136
this NPE was preventing jenkins workers from being deleted when they should have been.
I added a defaults class that will be used when parent cloud cannot be resolved
due to whatever reason.

JENKINS-29136 fix NPE in getRetentionTime()

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate.java

fixes JENKINS-22587.
`NovaTemplateOptions` class has its own `securityGroupNames` field. Other services use this field when operate with instance of `NovaTemplateOptions`.
So I set this field when `templateOptions` object is an instance of `NovaTemplateOptions`.

[JENKINS-22587] JClouds does not honor security group against OpenStack

---

jclouds-plugin/pom.xml
jclouds-plugin/src/main/resources/index.jelly
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/blobstore/BlobStoreEntry/config.jelly
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/blobstore/BlobStorePublisher/config.jelly
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/blobstore/BlobStorePublisher/global.jelly
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/InstancesToRun/config.jelly
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/InstancesToRun/help-suspendOrTerminate.jelly
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsBuildWrapper/config.jelly
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsCloud/computerSet.jelly
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsCloud/config.jelly
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsComputer/configure.jelly
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsCloudTest.java
pom.xml

* Updates jclouds and the maven-hpi-plugin to their latest stable versions.
* Fixes (and reactivate) some tests.
* Fixes of jelly files for preventing possible XSS attacks.
* Increases compiler verbosity (show warnings and deprecations).

Update to jclouds 1.9.1 and hpi-plugin 1.114

---

jclouds-plugin/pom.xml
jclouds-shaded/pom.xml
pom.xml

Removed unnecessary dependencies and consolidated setup for shading and hpi-plugin
Now there is only **one** setting in the toplevel pom pluginManagement.
Before, settings were duplicated in the sub modules and difficult to track.
Conflicts:
pom.xml

pom cleanup

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsCloud.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate.java

Fixes JENKINS-28815 circumventing jcloud's default image caching.

[JENKINS-28815] Providing nodes by "Image name" always works as by "Image ID"

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlave.java

Fixes JENKINS-30556 using a (admittingly ugly) woraround.

[JENKINS-30556] Cannot reconnect to running slaves after jenkins restart

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsCloud.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/internal/CredentialsHelper.java
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsCloud/config.jelly
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsCloud/help-cloudCredentialsId.html
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsCloud/help-credential.html
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsCloud/help-identity.html
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate/config.jelly
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/ComputeTestFixture.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsCloudInsideJenkinsLiveTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsCloudLiveTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsCloudTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplateTest.java

This one converts the old identity/credential pair into a Credentals object. (as usual: fully backwards compatible wit auto-migration).
This could also potentially solve the multiline requirement from #87 , but I need feedback on the exact key format before I can enable that.

Credentials migration, next step

---

.gitignore
jclouds-shaded/pom.xml

DigitalOcean API v1 will sunset in a few days: https://developers.digitalocean.com/documentation/changelog/api-v1/sunsetting-api-v1/
This PR changes the provider to use the version 2 of the api. However, this will break any existing configuration that uses the v1 provider as the credentials have changed. Users will have to generate an OAuth token in the DigitalOcean console and update the credentials accordingly (the v2 does not support the old clientid/apikey authentication).

Upgrade to DigitalOcean v2

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsLauncher.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlave.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate.java
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate/config.jelly
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplateTest.java

Using BitVise SSH Server (e.g. not using Cygwin+sshd) would fail to copy the `slave.jar` onto Windows instance due to the destination location `/tmp'. This change allows the indication of a Windows image when adding/configuring a Cloud Instance Template to properly copy and execute the slave.jar on Windows instance using Command Prompt (or PowerShell).

Address copying and executing slave.jar on Windows Slave

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsCloud.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate.java

```
reference to lookupCredentials is ambiguous both method
<C>lookupCredentials(java.lang.Class<C>,hudson.model.ItemGroup,org.acegisecurity.Authentication,com.cloudbees.plugins.credentials.domains.DomainRequirement...)
in com.cloudbees.plugins.credentials.CredentialsProvider and method
<C>lookupCredentials(java.lang.Class<C>,hudson.model.ItemGroup,org.acegisecurity.Authentication,java.util.List<com.cloudbees.plugins.credentials.domains.DomainRequirement>)
in com.cloudbees.plugins.credentials.CredentialsProvider match
```

Fixing build issues due to ambiguous method call [lookupCredentials]

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/blobstore/BlobStorePublisher.java

I want to manage the configured blobstore profiles with a Groovy script. This lets me do something like this:
```groovy
// Get credentials from somewhere and build a list of profiles...
BlobStorePublisher.DESCRIPTOR.setProfiles(profiles)
BlobStorePublisher.DESCRIPTOR.save()
```
Maybe there's a better way to do that, but I couldn't find one.

Add setProfiles method to BlobStorePublisher DescriptorImpl

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate.java

The credentials to get the admin user are pulled from normal credentials, not admin.   This fix resolves it.

Fix admin credentials

---

jclouds-plugin/pom.xml
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/UserData.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/config/AbstractJCloudsConfigProviderImpl.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/config/ConfigHelper.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/config/UserDataBoothook.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/config/UserDataInclude.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/config/UserDataIncludeOnce.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/config/UserDataPartHandler.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/config/UserDataScript.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/config/UserDataUpstart.java
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/config/UserDataYaml.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/MigrationTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/UserDataConverterTest.java

Update to support latest config-file-provider version.
Although the latest config-file-provider now supports configuration files on folder level, this PR updates the jcloud plugin to support on global scope only - which is the same as it was before this update.
To support folders, one would have to update all occurrences of `final Config cfg = ConfigFiles.getByIdOrNull(Jenkins.getActiveInstance(), id);` to use the correct scope object, e.g. the current build instead of `Jenkins.getActiveInstance()`.
e.g. in `jenkins.plugins.jclouds.config.ConfigHelper#getConfig`
Note: I'm not familiar with the usage of the jclouds plugin and therefore I was not able to test this in a real scenario. 
cc @felfert

JENKINS-41078 support latest config-file-provider plugin (2.15.4)

---

jclouds-shaded/pom.xml

The Packet provider has been in labs for a while and it is proven to be very stable. There is actually a PR to promote it to the main repo in the next jclouds major release: https://github.com/jclouds/jclouds/pull/1103.
This PR adds the Packet provider, so we can start using it without waiting for the next jclouds major, since there is no official date for it yet.

Added the Packet provider

---

jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/blobstore/BlobStoreProfile/config.jelly
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/InstancesToRun/config.jelly
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsCloud/config.jelly
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate/config.jelly

[JENKINS-55787](https://issues.jenkins-ci.org/browse/JENKINS-55787)
Basically checkboxes should have labels, splitting the labels away from their checkboxes is poor UX, poor accessibility. This change brings the layout more inline with how normal settings UIs lay out checkboxes.
Without this change, using current table ui:
With this change, using current table ui:
Without this change, using the table-less ui:
With this change, using the table-less ui:

[JENKINS-55787] Switch labels from entry to checkbox

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate.java

According to [documentation](https://jclouds.apache.org/guides/aws-ec2/) this should fix https://issues.jenkins-ci.org/browse/JENKINS-47301.
I see that JClouds doesn't use `networks` option for anything in AWS EC2.
So, it is OK to reuse existing option in plugin.
However, this should probably be fixed in JClouds.

Use networks setting for AWS EC2 subnetId

---

jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate.java
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate/config.jelly
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplateTest.java
jclouds-plugin/src/test/java/jenkins/plugins/jclouds/compute/MigrationTest.java

Since 2015, `jclouds` supports preemptible options on Google Container Engine: [JCLOUDS-1001](https://issues.apache.org/jira/browse/JCLOUDS-1001). 
As requested by users @ [JENKINS-44601](https://issues.jenkins-ci.org/browse/JENKINS-44601), I added the possibility to create instances on GCE with `preemptible` options. 
It has been tested on our Jenkins and VMs have been populated with preemptible option.

Add Preemptible option for GCP 

---

README.md

The plugin site will use data from the update center API and display this in a standard way for all plugins, no need to duplicate it

Remove security warning

---

jclouds-plugin/pom.xml

[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …

[SECURITY] Use HTTPS to resolve dependencies in Maven Build

---

README.md
jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsOneOffSlave.java

Jenkins project has officially deprecated the "slave" terminology in 2016. Let's clean it up here! I updated the README and JCloudsOneOffSlave, but I have not updated other entities yet. It could be done in the follow-up.
See https://issues.jenkins-ci.org/browse/JENKINS-62833

[JENKINS-62833] - Update the terminology in README and JCloudsOneOffSlave

---

jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/blobstore/BlobStoreProfile/config.jelly
jclouds-plugin/src/main/resources/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate/config.jelly
jclouds-plugin/src/main/resources/lib/jclouds/blockWrapper.jelly

Easier to test with https://github.com/jenkinsci/jclouds-plugin/pull/142
Following https://www.jenkins.io/doc/developer/views/table-to-div-migration/
See https://www.jenkins.io/blog/2020/11/10/major-changes-in-weekly-releases/
I'm not sure if this is causing an issue but I'm working through all the plugins that appear with tabular markup in https://issues.jenkins.io/browse/JENKINS-64341

JENKINS-64537 Compatibility with Jenkins core >=2.264

---

src/main/java/jenkins/plugins/jclouds/compute/JCloudsBuildWrapper.java

This method was deprecated in jenkinsci/jenkins#5467, so migrate away from it in favor of native Java Platform functionality.

Stop using deprecated `Util#join`

---

.mvn/extensions.xml
.mvn/maven.config
pom.xml
src/main/java/jenkins/plugins/jclouds/blobstore/BlobStoreProfile.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsBuildWrapper.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsCleanupThread.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsCloud.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsComputer.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlave.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsSlaveTemplate.java
src/main/java/jenkins/plugins/jclouds/compute/JCloudsStartupHandler.java
src/main/java/jenkins/plugins/jclouds/compute/UserData.java
src/main/java/jenkins/plugins/jclouds/compute/internal/JCloudsNodeMetadata.java
src/main/java/jenkins/plugins/jclouds/compute/internal/ProvisionPlannedInstancesAndDestroyAllOnError.java
src/main/java/jenkins/plugins/jclouds/compute/internal/TerminateNodes.java
src/main/java/jenkins/plugins/jclouds/config/ConfigDataSource.java
src/main/java/jenkins/plugins/jclouds/config/ConfigHelper.java
src/main/java/jenkins/plugins/jclouds/internal/ReplaceHelper.java
src/main/resources/META-INF/hudson.remoting.ClassFilter
src/test/java/jenkins/plugins/jclouds/blobstore/BlobStoreProfileTest.java
src/test/java/jenkins/plugins/jclouds/blobstore/BlobStoreTestFixture.java
src/test/java/jenkins/plugins/jclouds/compute/ComputeTestFixture.java
src/test/java/jenkins/plugins/jclouds/compute/JCloudsProfileTest.java
src/test/java/jenkins/plugins/jclouds/compute/internal/TerminateNodesTest.java

**Untested** PR to switch this plugin from using shaded/bundled copies of Guava/Guice to the (newly upgraded) versions of Guava and Guice in Jenkins core 2.321 and later. Note that this raises the minimum Jenkins version to a weekly (2.321). It also means we stop bundling Guava and Guice in this plugin. This should simplify maintenance by making everything less complicated.

Stop shading Guava/Guice

---

src/main/java/jenkins/plugins/jclouds/internal/SSHPublicKeyExtractor.java

JAXB has been removed in Java 9+, so use the Java Platform's built-in class instead. CC @felfert

Use built-in Base64 encoder

---

src/main/resources/jenkins/plugins/jclouds/credentials/JCloudsUserWithKey/credentials.jelly

see https://github.com/jenkinsci/jenkins/pull/7452
(untested but should be fine from what I can see in the PR as most of the inputs didn't have classes before)

Apply upcoming core styling to file upload

---

src/main/resources/jenkins/plugins/jclouds/compute/JCloudsCloud/computerSet.jelly

Follow up of https://github.com/jenkinsci/jenkins/pull/7573.
This has no effect on older versions of Jenkins. On newer versions of Jenkins this prevents a bug that I've briefly described in the PR linked above.

Use `Cloud#getUrl` in /provision URL

---

pom.xml

This adds a workaround for [JENKINS-72475](https://issues.jenkins.io/browse/JENKINS-72475) by masking `com.google.gson.`
The actual fix will be in jclouds-2.6.0 (which is not yet released)
```[tasklist]
```

Fixed JENKINS-72475

---

pom.xml

Updating jenkins base version and corresponding BOM configuration. Made relevant changes to resolve issues with dependencies.
Tests passed

updating jenkins base version and bom configuration

---

pom.xml
src/main/java/jenkins/plugins/jclouds/modules/JenkinsBouncyCastleCrypto.java

Without dropping compatibility with Guice 6 (currently delivered by Jenkins core), add support for Guice 7.

Forward compatibility with Guice 7

---

pom.xml

Replaced org.apache.jclouds.provider:digitalocean2 v2.5.0 by com.github.felfert:digitalocean2-fixed v2.5.2
This fixes a NumberFormatException when creating a droplet.
This is a backported fix of [this PR](https://github.com/apache/jclouds/pull/216) in upstream.

Fixed NumberFormatException in digitalocean2 provider

---

src/main/java/jenkins/plugins/jclouds/internal/SSHPublicKeyExtractor.java
src/test/java/jenkins/plugins/jclouds/internal/SSHPublicKeyExtractorTest.java

This PR adds support for `ecdsa-sha2-nistp256` and `ssh-ed25519` to SSHPublicKeyExtractor
Extended test class accordingly

Support modern keys in SSHPublicKeyExtractor
